apiVersion: v1
kind: Service
metadata:
  name: {{ include "arch-hw02.fullname" . }}
  labels:
    {{- include "arch-hw02.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "arch-hw02.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      name: web
    - port: {{ .Values.service.actuator.port }}
      targetPort: actuator
      name: actuator