{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "arch-hw02.fullname" . }}
  labels:
    {{- include "arch-hw02.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "arch-hw02.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "arch-hw02.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      port: actuator
      path: /actuator/prometheus
  {{- end }}