{
 "title": "HW-03",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "App - Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, (sum by (le,uri) (rate(http_server_requests_seconds_bucket{}[1m])))) * 1000",
       "legendFormat": "0.5 - {{ uri }}"
      },
      {
       "expr": "histogram_quantile(0.95, (sum by (le,uri) (rate(http_server_requests_seconds_bucket{}[1m])))) * 1000",
       "legendFormat": "0.95 - {{ uri }}"
      },
      {
       "expr": "histogram_quantile(0.95, (sum by (le,uri) (rate(http_server_requests_seconds_bucket{}[1m])))) * 1000",
       "legendFormat": "0.99 - {{ uri }}"
      }
     ]
    },
    {
     "title": "App - RPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count[1m])) by(uri)",
       "legendFormat": "{{ uri }}"
      }
     ]
    },
    {
     "title": "App - 5xx",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (increase(http_server_requests_seconds_count{status=~\"5.*\"}[1m]))",
       "legendFormat": "{{ uri }}"
      }
     ]
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Ingress - Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le,path) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"arch-hw02\"}[1m])))) * 1000",
     "legendFormat": "0.5 - {{ path }}"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le,path) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"arch-hw02\"}[1m])))) * 1000",
     "legendFormat": "0.95 - {{ path }}"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le,path) (rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"arch-hw02\"}[1m])))) * 1000",
     "legendFormat": "0.99 - {{ path }}"
    }
   ]
  },
  {
   "title": "Ingress - RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"arch-hw02\"}[1m])) by (path)",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Ingress - 5xx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{ingress=\"arch-hw02\",status =~\"5.*\"}[1m]))"
    }
   ]
  }
 ]
}