replicaCount: 2

image:
  app: giggaherzz/arch-hw02:latest
  flyway: boxfuse/flyway

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: arch.homework
  path: /otusapp/victor($|/)(.*)

postgresql:
  host: pg-postgresql
  postgresqlUsername: user
  postgresqlPassword: pass
  postgresqlDatabase: hw02
  service:
    port: 5432